Repository gdsc-bit/Important-Algorithms, pull requests merged in 2022-10, with the labels that each got.

#6 General Theory of Greedy Algorithm
  Greedy Algorithms/General Theory
Labels: documentation, hacktoberfest, hacktoberfest22, hacktoberfest-accepted, hacktoberfest2022

#9 Create Kruskal Algorithm theory.md
  Greedy Algorithms/Kruskal Algorithm/Theory.md
Labels: hacktoberfest, hacktoberfest22, hacktoberfest-accepted, hacktoberfest2022

#10 Kruskal.cpp uploaded
  Greedy Algorithms/Kruskal Algorithm/Kruskal.cpp
Labels: hacktoberfest, hacktoberfest22, hacktoberfest-accepted, hacktoberfest2022

#11 Insertion sort theory
  Sorting Algorithms/Insertion Sort/Theory.md
Labels: hacktoberfest, hacktoberfest22, hacktoberfest-accepted, hacktoberfest2022

#12 Implementation of Insertion Sort in java
  Sorting Algorithms/Insertion Sort/Insertion_Sort.java
Labels: hacktoberfest, hacktoberfest22, hacktoberfest-accepted, hacktoberfest2022

#14 I have uploaded mergesort.c file
  Sorting Algorithms/mergesort.c
Labels: hacktoberfest, hacktoberfest22, hacktoberfest-accepted, hacktoberfest2022

#15 Binary Search Theory
  Searching Algorithms/Binary Search/Theory.md
Labels: hacktoberfest, hacktoberfest22, hacktoberfest-accepted, hacktoberfest2022

#16 Implementation of Binary Search in Java
  Searching Algorithms/Binary Search/Binary_Search.java
Labels: hacktoberfest, hacktoberfest22, hacktoberfest-accepted, hacktoberfest2022

#18 Update JavaImplementation.java
  Dynamic Programming/0-1 Knapsack/JavaImplementation.java
Labels: hacktoberfest, hacktoberfest22, hacktoberfest-accepted, hacktoberfest2022

#19 Create Travelling Salesman Problem
  Dynamic Programming/Travelling Salesman problem/JavaImplementation.java
Labels: hacktoberfest, hacktoberfest22, hacktoberfest-accepted, hacktoberfest2022

#20 Added Counting Sort
  Greedy Algorithms/Counting Sort Algorithm/CountingSort.java
Labels: hacktoberfest, hacktoberfest22, hacktoberfest-accepted, hacktoberfest2022

#24 added the code
  Greedy Algorithms/Djisktra's algorithm/Djisktra's_algo.cpp
Labels: hacktoberfest, hacktoberfest22, hacktoberfest-accepted, hacktoberfest2022

#25 Create Algorithm for Tower of Hanoi
  Recursive Algorithm/Tower of Hanoi/Algorithm.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#28 Added some algorithms
  BackTracking/N Queen Problem/Nqueen.cpp
  Dynamic Programming/Kadane's Algorithm/kadane.c
  Recursive Algorithm/Factorial/factorial.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#29 Added Binary Search Tree Insertion
  Searching Algorithms/Binary Search/Binary_Search_Tree_Insertion.cpp
Labels: hacktoberfest, hacktoberfest22, hacktoberfest-accepted, hacktoberfest2022

#30 To find GCD of 2 numbers
  GCD/euclid's_algorithm.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#31 Added greedy algoritms
  Greedy Algorithms/Prim's Algorithm/Prims.java
Labels: enhancement, hacktoberfest, hacktoberfest22, hacktoberfest-accepted, hacktoberfest2022

#32 Create Theory.md
  Greedy Algorithms/Prim's Algorithm/Theory.md
Labels: enhancement, hacktoberfest, hacktoberfest22, hacktoberfest-accepted, hacktoberfest2022

#34 Radix sort theory
  Sorting Algorithms/Radix Sort/Theory.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#38 Added fibonacci search algorithm code
  .vscode/tasks.json
  Searching Algorithms/Fibonacci_Search/Fibonacci_search.cpp
  Searching Algorithms/Fibonacci_Search/Theory.md
  Searching Algorithms/Sentinel_search/Theory.md
  Searching Algorithms/Sentinel_search/sentinel_search.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#41 Added code for Fibonacci Search and Merge Sort in Java
  Searching Algorithms/Fibonacci_Search/FibonacciSearch.java
  Sorting Algorithms/Merge Sort/MergeSort.java
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#42 Bubble Sort using Recursion
  Recursive Algorithm/bubble_sort_recursion.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#44 painting algo added
  Dynamic Programming/Painting Fence Algorithm/painting_fence_algo.cpp
  Dynamic Programming/painting_fence_algo/painting_fense_algo.cpp
Labels: enhancement, hacktoberfest-accepted

#45 ford algo add
  Dynamic Programming/Floyd Warshall Algorithm/Floyd Warshall Algorithm.cpp
  Greedy Algorithms/Dial’s Algorithm/Dial’s Algorithm.cpp
  Greedy Algorithms/Ford-Fulkerson Algorithm/Ford-Fulkerson-Algorithm.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
